#!/usr/bin/env bash
# The file /etc/passwd has already been covered in a previous project and you should be familiar with it. Today we will make up a story based on it
while IFS=: read -r USERNAME PASSWORD USER_ID GROUP_ID USER_INFO HOME_DIRECTORY COMMAND
do 
 echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_INFO"
done < /etc/passwd

awk '{print $1, $9}' apache-access.log
